// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHubTestProjectVisualStudioExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitHubTestProjectVisualStudioExtension.32d2917c-09fd-46bd-b2fc-79c9b6000b4e";
        public const string Name = "GitHubTestProjectVisualStudioExtension";
        public const string Description = @"VSIX Project used to test GitHub Actions";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rémi Morillon";
        public const string Tags = "";
    }
}
