name: Validate .NET
description: Validate your .NET repository.
inputs:
  configuration:
    description: Configuration to build.
    required: false
    default: Release
runs:
  using: composite
  env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_ARGUMENTS: --nologo -c ${{ inputs.configuration }}
  steps:
  - name: Install dotnet
    uses: actions/setup-dotnet@v1
  - name: Restore
    run: dotnet restore
  - name: Build
    run: dotnet build --no-restore $DOTNET_ARGUMENTS
  - name: Test
    run: dotnet test --no-build $DOTNET_ARGUMENTS
  - name: Publish
    run: dotnet publish --no-build $DOTNET_ARGUMENTS
  - name: Pack
    run: dotnet pack --no-build $DOTNET_ARGUMENTS
