// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHubTestProjectVisualStudio17Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitHubTestProjectVisualStudio17Extension.f0f60515-8792-4def-9eda-cf73150c0926";
        public const string Name = "GitHubTestProjectVisualStudio17Extension";
        public const string Description = @"VSIX Project used to test GitHub Actions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Rémi Morillon";
        public const string Tags = "";
    }
}
