// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace GitHubTestProjectVisualStudio17Extension
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitHubTestProjectVisualStudio17ExtensionString = "8485dde2-6425-448e-a359-b9f771b0519e";
        public static Guid GitHubTestProjectVisualStudio17Extension = new Guid(GitHubTestProjectVisualStudio17ExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}