name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  dotnet-validate:
    name: dotnet
    uses: ReMinoer/GitHubTestProject/.github/workflows/dotnet-validate.yml@master
