name: Changes
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  valide:
    name: Validate
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release
