name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  valide:
    name: Validate
    runs-on: ubuntu-latest
    env:
      DOTNET_ARGUMENTS: --nologo -c Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore $DOTNET_ARGUMENTS
    - name: Test
      run: dotnet test --no-build $DOTNET_ARGUMENTS
    - name: Publish
      run: dotnet publish --no-build $DOTNET_ARGUMENTS
    - name: Pack
      run: dotnet pack --no-build $DOTNET_ARGUMENTS
