name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  dotnet:
    name: .NET
    uses: ReMinoer/GitHubTestProject/.github/workflows/dotnet-validate.yml@master
