name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  dotnet-validate:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-validate.yml@master
    with:
      solution_file: GitHubTestProject.sln
      dotnet_version: 3.1
  installer-validate:
    name: installer
    uses: ReMinoer/workflows/.github/workflows/installer-validate.yml@master
    with:
      solution_file: GitHubTestProject.sln
      installer_project_file: src/GitHubTestProject.Tool.Installer/GitHubTestProject.Tool.Installer.vdproj
      installer_configuration_suffix: '_Installer'
      dotnet_version: 3.1
  vsix-validate:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-validate.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      dotnet_version: 3.1
