name: dotnet / Release
on:
  workflow_call:
    inputs:
      project_folder:
        required: true
        type: string
      target_framework:
        required: true
        type: string
      zip_prefix:
        required: true
        type: string
      configuration:
        required: false
        type: string
        default: Release
defaults:
  run:
    shell: bash
env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_ARGUMENTS: --nologo -c ${{ inputs.configuration }}
  MSBUILD_PROPERTIES: >
    -p:Authors=${{ github.repository_owner }}
    -p:PackageProjectUrl=https://github.com/${{ github.repository }}
    -p:RepositoryUrl=https://github.com/${{ github.repository }}.git
    -p:RepositoryBranch=master
    -p:RepositoryCommit=${{ github.sha }}
  PUBLISH_FOLDER: ${{ inputs.project_folder }}/bin/${{ inputs.configuration }}/${{ inputs.target_framework }}/publish
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      ZIP_FILENAME: ${{ inputs.zip_prefix }}-${{ runner.os }}.zip
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Parse Tag
      uses: dawidd6/action-get-tag@v1
      id: tag
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore $DOTNET_ARGUMENTS $MSBUILD_PROPERTIES -p:Version=${{ steps.tag.outputs.tag }}
    - name: Test
      run: dotnet test --no-build $DOTNET_ARGUMENTS
    - name: Publish
      run: dotnet publish --no-build $DOTNET_ARGUMENTS
    - name: Zip
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{ env.ZIP_FILENAME }}'
        directory: '${{ env.PUBLISH_FOLDER }}'
    - name: Release
      uses: alexellis/upload-assets@0.3.0
      with:
        asset_paths: '["${{ env.PUBLISH_FOLDER }}/${{ env.ZIP_FILENAME }}"]'
      env:
        GITHUB_TOKEN: ${{ github.token }}
