name: Releases
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
    - name: Parse Tag
      uses: dawidd6/action-get-tag@v1
      id: tag
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{steps.tag.outputs.tag}}
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release -p:Version=${{steps.tag.outputs.tag}}
    - name: Push
      run: dotnet nuget push **/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
