name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/GitHubTestProject/.github/workflows/dotnet-release.yml@master
    with:
      project_folder: src/GitHubTestProject.Tool
      target_framework: netcoreapp3.1
      zip_prefix: githubtesttool
  dotnet-nuget:
    needs: dotnet-release
    name: dotnet
    uses: ReMinoer/GitHubTestProject/.github/workflows/dotnet-nuget.yml@master
    secrets:
      sources_folder: src
      nuget_token: ${{ secrets.NUGET_TOKEN }}