name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      solution_file: GitHubTestProject.sln
      project_folder: src/GitHubTestProject.Tool
      target_framework: netcoreapp3.1
      zip_prefix: githubtesttool
  vsix-release-2019:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudioExtension
      vsix_name: GitHubTestProjectVisualStudioExtension
  vsix-release-2022:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudio17Extension
      vsix_name: GitHubTestProjectVisualStudio17Extension
  dotnet-nuget:
    needs: dotnet-release
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-nuget.yml@master
    with:
      solution_file: GitHubTestProject.sln
      sources_folder: src
    secrets:
      nuget_token: ${{ secrets.NUGET_TOKEN }}
  vsix-publish-2019:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudioExtension
      vsix_name: GitHubTestProjectVisualStudioExtension
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}
  vsix-publish-2022:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudio17Extension
      vsix_name: GitHubTestProjectVisualStudio17Extension
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}