name: Releases
on: [release]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Parse Tag
      uses: dawidd6/action-get-tag@v1
      id: tag
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{steps.tag.outputs.tag}}
    - name: Test
      run: dotnet test --no-build -c Release
    - name: Pack
      run: dotnet pack --no-build -c Release
    - name: Push
      run: dotnet nuget push "*.nupkg"
