name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      solution_file: GitHubTestProject.sln
      project_folder: src/GitHubTestProject.Tool
      target_framework: netcoreapp3.1
      zip_prefix: githubtesttool
      dotnet_version: 3.1
  vsix-release-2019:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudioExtension
      vsix_name: GitHubTestProjectVisualStudioExtension
      dotnet_version: 3.1
  vsix-release-2022:
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-release.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudio17Extension
      vsix_name: GitHubTestProjectVisualStudio17Extension
      dotnet_version: 3.1
  installer-release:
    name: installer
    uses: ReMinoer/workflows/.github/workflows/installer-release.yml@master
    with:
      solution_file: GitHubTestProject.sln
      project_folder: src/GitHubTestProject.Tool.Installer
      installer_name: GitHubTestProject.Tool.Installer
      installer_configuration_suffix: '_Installer'
      dotnet_version: 3.1
  dotnet-nuget:
    needs: dotnet-release
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-nuget.yml@master
    with:
      solution_file: GitHubTestProject.sln
      sources_folder: src
      dotnet_version: 3.1
    secrets:
      nuget_token: ${{ secrets.NUGET_TOKEN }}
  vsix-publish-2019:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudioExtension
      vsix_name: GitHubTestProjectVisualStudioExtension
      dotnet_version: 3.1
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}
  vsix-publish-2022:
    needs: [vsix-release-2019, vsix-release-2022]
    name: vsix
    uses: ReMinoer/workflows/.github/workflows/vsix-publish.yml@master
    with:
      solution_file: GitHubTestProject.VSIX.sln
      project_folder: plugins/GitHubTestProjectVisualStudio17Extension
      vsix_name: GitHubTestProjectVisualStudio17Extension
      dotnet_version: 3.1
    secrets:
      marketplace_token: ${{ secrets.MARKETPLACE_TOKEN }}